### PR TITLE
replace uuid to object name

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Comment by Tianhao-Gu** [comment]
@samseaver Could you take a look? 

I am trying to replace uuid file prefix to object_name + reference.
Ticket: https://kbase-jira.atlassian.net/browse/PTV-636

**Comment by samseaver** [comment]
This looks like it'd work.

**Comment by Tianhao-Gu** [comment]
@samseaver Cool. Could you merge and deploy in appdev dev for testing?

**Comment by samseaver** [comment]
I don't have the power to merge in kbaseapps, so you'll have to ask someone on the implementation team, probably @scanon ?

**Pull request merged**
