### PR TITLE
Support for auth2

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by rsutormin** [comment]
@samseaver: Sam, can you please review this PR?

**Comment by samseaver** [comment]
It looks fine to me, would you like me to actually test auth2 with this module, locally?

**Comment by rsutormin** [comment]
@samseaver: No, I tested it with auth2 on my local machine. But if you can run it in CI (I just registered this version) in dev mode it would be good.

**Comment by samseaver** [comment]
I tested this in CI, in Dev, and it works fine, thanks!

**Pull request merged**
